stages:
  - Production
  - Tests

language: c

osx_image: 
  - xcode7.3

dist:
  - trusty
  - precise

os:
  - windows
  - linux
  - osx 

env:
  - PLATFORM=$TRAVIS_OS_NAME ARCH=32x86 FLAVOR=squeak.cog.spur
  - PLATFORM=$TRAVIS_OS_NAME ARCH=32x86 FLAVOR=pharo.cog.spur
  - PLATFORM=$TRAVIS_OS_NAME ARCH=64x64 FLAVOR=squeak.cog.spur
  - PLATFORM=$TRAVIS_OS_NAME ARCH=64x64 FLAVOR=pharo.cog.spur

#jobs:
#  include:
#    - stage: Production
#      env: FLAVOR=cog.spur
#    - stage: Stack builds
#      env: FLAVOR=stack.spur

script:
  - uname -a
  - env | sort
#  - find / -maxdepth 2 -print -name proc -prune || true
#  - find /proc -maxdepth 2
