language: c

osx_image: xcode7.3

name: "Production"

os:
  - windows
  - linux
  - osx 

env:
  - DIALECT=squeak
  - DIALECT=pharo

jobs:
  include:
    - stage: Cog builds
      env: FLAVOR=cog.spur
    - stage: Stack builds
      env: FLAVOR=stack.spur

script:
  - uname -a
  - env
  - find / -maxdepth 2 -print -name proc -prune || true
  # - find /proc -maxdepth 2
