language: c

osx_image: 
  - xcode7.3

dist: trusty

stages:
  - Production
  - Coverage
  - Experimental
  - Other

script:
  - if [ "${TRAVIS_BUILD_STAGE_NAME}" = "Coverage" ] ; then exit 1 ; fi  # simulate failure
  - exit 0  # simualte success


# Sections 'os:' and 'env:' are cross-tabulated to form the coverage matrix

stage: Coverage


env: [
    &E01 "BUILD=32x86/squeak.cog.spur     TESTIMAGE=Squeak32-5.1", 
    &E02 "BUILD=32x86/pharo.cog.spur      TESTIMAGE=Pharo32-5.0", 
    &E03 "BUILD=32x86/newspeak.cog.spur   TESTIMAGE=refer_newspeakBootstrap.sh", 
    &E04 "BUILD=32x86/squeak.cog.v3       TESTIMAGE=Squeak32-4.6",
]
os:
  -       linux
  -       osx 
#  -       windows


matrix:
  allow_failures:
    - stage: Coverage
  exclude: [
    &P01 { "os": "linux", "env": *E01 },
    &P02 { "os": "osx",   "env": *E02 },
  ]

aliases:
  &TEST CHROOT=xxxx

matrix:
  include: 
  - stage: Production
    <<: *P01
  - stage: Production
    <<: *P02

  - { "stage":"Experimental",  "os":"osx",    "env":"BUILD=32x86/pharo.sista.spur" }



#  include: [
#    # The travis_build.sh script expects these production jobs formatted like this to filter duplicates out of 'Test' stage.
#    { "stage":"Production",  	"os":"linux",	"env":"BUILD=32x86/squeak.cog.spur  TESTIMAGE=Squeak32-5.1"	}, 
#    { "stage":"Production",  	"os":"linux",	"env":"BUILD=32x86/pharo.cog.spur   TESTIMAGE=Pharo32-5.0" 	}, 
#    { "stage":"Production",  	"os":"osx",  	"env":"BUILD=32x86/squeak.cog.spur  TESTIMAGE=Squeak32-5.1" 	}, 
#    { "stage":"Production",  	"os":"osx",  	"env":"BUILD=32x86/pharo.cog.spur   TESTIMAGE=Pharo32-5.0" 	}, 
#    { "stage":"Production",  	"os":"linux",	"env":"BUILD=64x64/squeak.cog.spur  TESTIMAGE=skip" 		}, 
#    { "stage":"Production",  	"os":"linux",	"env":"BUILD=64x64/pharo.cog.spur   TESTIMAGE=skip" 		}, 
#    { "stage":"Production",  	"os":"osx",  	"env":"BUILD=64x64/squeak.cog.spur  TESTIMAGE=skip" 		}, 
#    { "stage":"Production",  	"os":"osx",  	"env":"BUILD=64x64/pharo.cog.spur   TESTIMAGE=skip" 		}, 
#
#    { "stage":"Experimental",	"os": "osx", 	"env": "BUILD=32x86/pharo.sista.spur"							}, 
#    { "stage":"Experimental",	"os": "linux", 	"env": "BUILD=32x86/squeak.sista.spur" 							}, 
#    { "stage":"Experimental",	"os": "linux", 	"env": "BUILD=32x86/squeak.sista.spur TESTFAIL=1" 					}, 
##    { "stage":"Experimental",	"os": "linux", 	"env": "BUILD=32x86/pharo.sista.spur 	HEARTBEAT=threaded", 	"compiler": "clang" 	}, 
#    { "stage":"Experimental",	"os": "linux", 	"env": "BUILD=32x86/pharo.sista.spur 	HEARTBEAT=itimer", 	"compiler": "clang" 	}, 
#    { "stage":"Experimental",	"os": "osx", 	"env": "BUILD=32x86/pharo.cog.spur.lowcode" 						}, 
#    { "stage":"Experimental",	"os": "osx", 	"env": "BUILD=64x64/pharo.cog.spur.lowcode" 						}, 
#    { "stage":"Experimental",	"os": "osx", 	"env": "BUILD=32x86/pharo.stack.spur.lowcode" 						}, 
#    { "stage":"Experimental",	"os": "osx", 	"env": "BUILD=64x64/pharo.stack.spur.lowcode" 						}, 
#
#    { "stage":"Other", 		"os":"linux",	"env": "BUILD=32ARMv6/newspeak.cog.spur   CHROOT=\"schroot -p -c rpi -- bash -c\"", "group": "edge" }, 
#    { "stage":"Other", 		"os":"linux", 	"env": "BUILD=32ARMv6/newspeak.stack.spur CHROOT=\"schroot -p -c rpi -- bash -c\"", "group": "edge" }, 
#    { "stage":"Other", 		"os":"linux", 	"env": "BUILD=32ARMv6/squeak.cog.spur     CHROOT=\"schroot -p -c rpi -- bash -c\"", "group": "edge" }, 
#    { "stage":"Other", 		"os":"linux", 	"env": "BUILD=32ARMv6/pharo.cog.spur      CHROOT=\"schroot -p -c rpi -- bash -c\"", "group": "edge" }, 
#    { "stage":"Other", 		"os":"linux", 	"env": "BUILD=32ARMv6/squeak.stack.spur   CHROOT=\"schroot -p -c rpi -- bash -c\"", "group": "edge" }, 
#    { "stage":"Other", 		"os":"linux", 	"env": "BUILD=32ARMv6/squeak.stack.v3     CHROOT=\"schroot -p -c rpi -- bash -c\"", "group": "edge" },

    # Faster builds later makes best use of early finishing slow jobs.
#    { "stage":"Other", 		"os":"linux", 	"env": "BUILD=32x86/pharo.cog.spur  	HEARTBEAT=itimer" }, 
#    { "stage":"Other", 		"os":"linux", 	"env": "BUILD=64x64/pharo.cog.spur      HEARTBEAT=itimer" }

#  ]


