language: c

osx_image: 
  - xcode7.3

dist: trusty

stages:
  - Production
  - Coverage
  - Experimental
  - Other

# Sections 'os:' and 'env:' are cross-tabulated to form the coverage matrix
# The travis_build.sh script ensures 'Production' builds are not built twice.
stage: Coverage
env:
  - BUILD=64x64/squeak.cog.spur     TESTIMAGE=skip
  - BUILD=64x64/pharo.cog.spur      TESTIMAGE=skip    		

  - BUILD=32x86/squeak.cog.spur    TESTIMAGE=Squeak32-5.1
  - BUILD=32x86/pharo.cog.spur     TESTIMAGE=Pharo32-5.0
os:
  -       linux
#  -       osx 
#  -       windows

matrix:
  fast_finish: true

  allow_failures:  # Note, 'env:' here string matches whole line *eactly* space for space, not individual vars
  - stage: Experimental
#  - stage: Coverage  # Temporary, for demonstration only
#  - stage: Other     # Temporary, for demonstration only
 
  include: [
    # The travis_build.sh script expects these production jobs formatted like this to filter duplicates out of 'Test' stage.
    { "stage":"Production",  	"os":"linux",	"env":"BUILD=64x64/squeak.cog.spur     TESTIMAGE=skip"		},
    { "stage":"Production",  	"os":"linux",	"env":"BUILD=64x64/pharo.cog.spur      TESTIMAGE=skip"    	},

    { "stage":"Experimental",	"os": "linux", 	"env": "BUILD=32x86/squeak.sista.spur" 							}, 
    { "stage":"Experimental",	"os": "linux", 	"env": "BUILD=32x86/squeak.sista.spur" 							}, 
    { "stage":"Experimental",	"os": "linux", 	"env": "BUILD=32x86/pharo.sista.spur 	HEARTBEAT=threaded", 	"compiler": "clang" 	}, 
    { "stage":"Experimental",	"os": "linux", 	"env": "BUILD=32x86/pharo.sista.spur 	HEARTBEAT=itimer", 	"compiler": "clang" 	}, 

  ]

#before_install:
#  - ./travis_cancel_dup_prod_job.sh

script:
  - ./travis_build.sh 

