language: c

os:
  - windows
  - linux
  - osx

env:
  - DIALECT=squeak
  - DIALECT=pharo

env:
  - FLAVOR=cog.spur
  - FLAVOR=stack.spur

script:
  - uname -a
  - env
  - find / -maxdepth 2 -print -name proc -prune || true
  # - find /proc -maxdepth 2
