stages:
  - Production
  - Tests

language: c

osx_image: 
  - xcode7.3

dist:
  - trusty
  - precise

os:
  - windows
  - linux
  - osx 

env:
  - AAA1=build.$TRAVIS_OS_NAME  AAA2=32x86/squeak.cog.spur
#  - MATRIX=32x86/pharo.cog.spur
#  - MATRIX=64x64/squeak.cog.spur
#  - MATRIX=64x64/pharo.cog.spur

#jobs:
#  include:
#    - stage: Production
#      env: FLAVOR=cog.spur
#    - stage: Stack builds
#      env: FLAVOR=stack.spur

script:
  - uname -a
  - env | sort
#  - find / -maxdepth 2 -print -name proc -prune || true
#  - find /proc -maxdepth 2
