stages:
  - Production
  - Tests

language: c

osx_image: 
  - xcode7.3

dist:
  - trusty
  - precise

os:
  - linux
  - osx 
  - windows

env:
  - ARCH=32x86  FLAVOR=squeak.cog.spur
  - ARCH=32x86  FLAVOR=pharo.cog.spur

  - ARCH=64x64  FLAVOR=squeak.cog.stack
  - ARCH=64x64  FLAVOR=pharo.cog.stack

#jobs:
#  include:
#    - stage: Production
#      env: FLAVOR=cog.spur
#    - stage: Stack builds
#      env: FLAVOR=stack.spur

script:
  - uname -a
  - echo BUILDING... build${PLATFORM}${ARCH}/${FLAVOR}
  - env | sort
#  - find / -maxdepth 2 -print -name proc -prune || true
#  - find /proc -maxdepth 2
