stages:
  - Production
  - Tests

language: c

osx_image: 
  - xcode7.3

dist:
  - trusty
  - precise

os:
  - linux
  - osx 
  - windows

env:
  - ARCH=64x64  FLAVOR=squeak.cog.spur
  - ARCH=64x64  FLAVOR=pharo.cog.spur      LINUX_HEARTBEAT=threaded
  - ARCH=64x64  FLAVOR=newspeak.cog.spur

  - ARCH=32x86  FLAVOR=squeak.cog.spur
  - ARCH=32x86  FLAVOR=pharo.cog.spur      LINUX_HEARTBEAT=threaded
  - ARCH=32x86  FLAVOR=newspeak.cog.spur
  - ARCH=32x86  FLAVOR=squeak.cog.v3

  - ARCH=64x64  FLAVOR=squeak.cog.stack
  - ARCH=64x64  FLAVOR=pharo.cog.stack   # linux not built
  - ARCH=64x64  FLAVOR=newspeak.cog.stack

  - ARCH=32x86  FLAVOR=squeak.cog.stack
  - ARCH=32x86  FLAVOR=pharo.cog.stack   # linux not built
  - ARCH=32x86  FLAVOR=newspeak.cog.stack
  - ARCH=32x86  FLAVOR=squeak.stack.v3

jobs:
  include:
    - stage: ADHOC LINUX BUILDS
      os: osx
      env:   ARCH=64x64  FLAVOR=pharo.cog.spur      LINUX_HEARTBEAT=itimer
    - env:   ARCH=32x86  FLAVOR=pharo.cog.spur      LINUX_HEARTBEAT=itimer
    - stage: ADHOC OTHER BUILDS
      env: FLAVOR=stack.spur

script:
  - uname -a
  - echo BUILDING... build${PLATFORM}${ARCH}/${FLAVOR}
  - env | sort
#  - find / -maxdepth 2 -print -name proc -prune || true
#  - find /proc -maxdepth 2
