language: c

osx_image: 
  - xcode7.3

dist:
  - trusty
  - precise

os:
  - windows
  - linux
  - osx 

env:
  - ARCH=32x86 FLAVOUR=squeak.cog.spur
  - ARCH=32x86 FLAVOUR=pharo.cog.spur
  - ARCH=64x64 FLAVOUR=squeak.cog.spur
  - ARCH=64x64 FLAVOUR=pharo.cog.spur

jobs:
  include:
    - stage: Cog builds
      env: FLAVOR=cog.spur
      name: "Cog"
    - stage: Stack builds
      env: FLAVOR=stack.spur
      name: "Stack"

script:
  - uname -a
  - env
  - find / -maxdepth 2 -print -name proc -prune || true
  # - find /proc -maxdepth 2
