language: c

os:
  - linux
  - osx 
  - windows

osx_image: 
  - xcode7.3

dist: trusty

stages:
  - Production
  - Tests

env:
  - ARCH=64x64  FLAVOR=squeak.cog.spur
  - ARCH=64x64  FLAVOR=pharo.cog.spur      LINUX_HEARTBEAT=threaded
  - ARCH=64x64  FLAVOR=newspeak.cog.spur

  - ARCH=32x86  FLAVOR=squeak.cog.spur
  - ARCH=32x86  FLAVOR=pharo.cog.spur      LINUX_HEARTBEAT=threaded
  - ARCH=32x86  FLAVOR=newspeak.cog.spur
  - ARCH=32x86  FLAVOR=squeak.cog.v3

  - ARCH=64x64  FLAVOR=squeak.cog.stack
  - ARCH=64x64  FLAVOR=pharo.cog.stack   # linux not built
  - ARCH=64x64  FLAVOR=newspeak.cog.stack

  - ARCH=32x86  FLAVOR=squeak.cog.stack
  - ARCH=32x86  FLAVOR=pharo.cog.stack   # linux not built
  - ARCH=32x86  FLAVOR=newspeak.cog.stack
  - ARCH=32x86  FLAVOR=squeak.stack.v3

jobs:
  include:
    - stage: ADHOC LINUX BUILDS

      os: linux
      env:   ARCH=64x64  FLAVOR=pharo.cog.spur      LINUX_HEARTBEAT=itimer

    - os: linux
      env:   ARCH=32x86  FLAVOR=pharo.cog.spur      LINUX_HEARTBEAT=itimer


    - stage: ADHOC MAC BUILDS

      os: osx
      env:   ARCH=32x86  FLAVOR=pharo.cog.spur.lowcode      LINUX_HEARTBEAT=itimer

    - os: osx
      env:   ARCH=32x86  FLAVOR=pharo.cog.spur      LINUX_HEARTBEAT=itimer


script:
  - uname -a
  - echo BUILDING... build${PLATFORM}${ARCH}/${FLAVOR}
  - env | sort
#  - find / -maxdepth 2 -print -name proc -prune || true
#  - find /proc -maxdepth 2
