language: ruby

os:
#  - windows
  - linux
  - osx 

osx_image: xcode7.3

env:
  - DIALECT=squeak
  - DIALECT=pharo

jobs:
  include:
    - stage: Cog builds
      env: FLAVOR=cog.spur
    - stage: Stack builds
      env: FLAVOR=stack.spur

gemfile:
  - Gemfile
  - gemfiles/rails4.gemfile
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile

script:
  - uname -a
  - env
  - find / -maxdepth 2 -print -name proc -prune || true
  # - find /proc -maxdepth 2
